// Auto-generated curated slice from data/benchmarks/cs302_final_fall2025/.
// 1 question (q7 - polynomial reduction) x 3 students = 3 grading calls.
// Matches the 'one-directional under-credit' calibration case from the slides.

import type { DemoQuestion } from './midterm1-slice'

export const demoQuestions: DemoQuestion[] = [
  {
    "question_id": "q7",
    "question": "A Hamiltonian path in an undirected or directed graph is a path that visits each vertex exactly once. A Tonian path in an undirected or directed graph is a path that visits at least half of the vertices in the graph. Let HAMILTONIAN and TONIAN be the problems of determining whether a graph has a Hamiltonian path and a Tonian path, respectively. Prove that HAMILTONIAN ≤p TONIAN, meaning that any instance of the HAMILTONIAN problem can be reduced in polynomial time to an instance of the TONIAN problem.",
    "max_score": 28,
    "benchmark_type": "polynomial_reduction"
  }
]

export const demoRubrics: Record<string, string> = {
  "q7": "- Correct construction: given G = (V, E) with |V| = n, construct G' as two disjoint copies of G with no edges between them, giving |V'| = 2n (0-6)\n- Forward direction (HAMILTONIAN → TONIAN): if G has a Hamiltonian path, then one copy of G in G' has a path visiting all n vertices, which is exactly n = |V'|/2 vertices, satisfying the Tonian condition (0-7)\n- Backward direction (TONIAN → HAMILTONIAN): if G' has a Tonian path visiting >= n vertices, and the two copies are disconnected, the path must lie entirely within one copy of G (which has exactly n vertices), so the path visits all n vertices — a Hamiltonian path in G (0-7)\n- Polynomial-time argument: the construction (copying V and E twice) runs in O(|V| + |E|) time (0-4)\n- Clear conclusion: since the construction is polynomial and the two instances are equivalent (G has a Hamiltonian path iff G' has a Tonian path), HAMILTONIAN ≤p TONIAN (0-4)\n\nGrading note: A complete reduction proof requires four components: the construction, the forward direction, the backward direction, and the polynomial-time argument. Missing any direction of correctness loses significant points. Award partial credit if construction is correct but one direction of proof is missing or flawed."
}

export const demoSubmissions: string = "[\n  {\n    \"student_id\": \"001\",\n    \"answers\": [\n      {\n        \"question_id\": \"q7\",\n        \"student_answer\": \"Construct a graph G' so that if G' has a Tonian path, by adding dummy vertices to G'(add m dummy nodes], we can always construct a graph G' from G and the TONIAN problem in G' is solved with the solution a -> b -> c -> d [4 out of 8 nodes]. Then Hamiltonian reduced to tonian, a -> b -> ... -> d is also the solution of Hamiltonian problem. Graph construction cost O(|V| + |E|). Check if that is valid tonian. => Hamiltonian ≤p tonian.\"\n      }\n    ]\n  },\n  {\n    \"student_id\": \"003\",\n    \"answers\": [\n      {\n        \"question_id\": \"q7\",\n        \"student_answer\": \"Given graph G=(V,E), construct G'=(V',E'). For all v_i ∈ V, add v_i1 and v_i2 to V'. Therefore |V'|=2|V|. [UNCERTAIN: crossed-out edge-construction line]. Now, visually G' looks like G duplicated. It basically has 2 of G's as 2 forests in G'. If there exists a Tonian path in G', it must be limited to 1 forest in G'. But because it contains 1/2 |V'| = |V|, the path must be connecting every node in that forest. That is the Hamiltonian path on G (half of G'). The reduction process is only building G'. It is in polynomial time O(|V|+|E|) ∈ O(n^2). Because there exists a polynomial time reduction, we have HAMILTONIAN ≤p TONIAN.\"\n      }\n    ]\n  },\n  {\n    \"student_id\": \"004\",\n    \"answers\": [\n      {\n        \"question_id\": \"q7\",\n        \"student_answer\": \"For the Tonian path, it may mean that that path visits at least half of the vertices in the graph, but not mention the vertex can be visited more than once. So changing the path existing in Hamiltonian is short path in Tonian and the path not existing in Hamiltonian is long path in Tonian. If it covers the shortest, meaning it covers the Hamiltonian. [UNCERTAIN: final incomplete phrase about Tonian].\"\n      }\n    ]\n  }\n]"

export const demoProfessorGrades: string = "[\n  {\n    \"student_id\": \"001\",\n    \"grades\": [\n      {\n        \"question_id\": \"q7\",\n        \"score\": 28,\n        \"score_max\": 28,\n        \"comment\": \"\"\n      }\n    ]\n  },\n  {\n    \"student_id\": \"003\",\n    \"grades\": [\n      {\n        \"question_id\": \"q7\",\n        \"score\": 28,\n        \"score_max\": 28,\n        \"comment\": \"\"\n      }\n    ]\n  },\n  {\n    \"student_id\": \"004\",\n    \"grades\": [\n      {\n        \"question_id\": \"q7\",\n        \"score\": 0,\n        \"score_max\": 28,\n        \"comment\": \"\"\n      }\n    ]\n  }\n]"
